name: CI

on: push

# Cancel in progress runs of this workflow when we push changes to the branch
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - '16'
          - '18'
          - '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run type checks
        run: npm run type-check

      - name: Run lint checks
        run: npm run lint

      - name: Run tests
        run: npm run test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run build
        run: npm run build

      - name: Install yalc
        run: npm install -g yalc

      - name: Yalc publish
        run: yalc publish

      - name: Delete top level node_modules
        run: rm -rf node_modules

      - name: Test CJS imports
        working-directory: e2e/test-import-cjs
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test

      - name: Test ESM imports
        working-directory: e2e/test-import-esm
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test

      - name: Test ESM imports frontend
        working-directory: e2e/test-import-esm-frontend
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test

      - name: Test CJS imports with langchain installed
        working-directory: e2e/test-import-cjs-langchain
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test

      - name: Test ESM imports with langchain installed
        working-directory: e2e/test-import-esm-langchain
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test

      - name: Test ESM imports & openai tracer
        working-directory: e2e/test-trace-openai-esm
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AUTOBLOCKS_API_KEY: ${{ secrets.CI_AUTOBLOCKS_API_KEY }}
          AUTOBLOCKS_INGESTION_KEY: ${{ secrets.CI_AUTOBLOCKS_INGESTION_KEY }}

      - name: Test ESM imports & API client
        working-directory: e2e/test-api-client-esm
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_API_KEY: ${{ secrets.CI_AUTOBLOCKS_API_KEY }}
          AUTOBLOCKS_INGESTION_KEY: ${{ secrets.CI_AUTOBLOCKS_INGESTION_KEY }}

      - name: Test Prompt Manager & TypeScript
        working-directory: e2e/test-prompt-manager-ts
        run: |
          yalc add @autoblocks/client && \
          npm install && \
          npm run ab-prompts-generate && \
          npm run start
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
