name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - '16'
          - '18'
          - '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run type checks
        run: npm run type-check

      - name: Run lint checks
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          AUTOBLOCKS_API_KEY: ${{ secrets.DEMO_AUTOBLOCKS_API_KEY }}
          AUTOBLOCKS_INGESTION_KEY: ${{ secrets.DEMO_AUTOBLOCKS_INGESTION_KEY }}

      - name: Run build
        run: npm run build
