name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - '16'
          - '18'
          - '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run type checks
        run: npm run type-check

      - name: Run lint checks
        run: npm run lint

      - name: Run tests
        run: npm run test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          AUTOBLOCKS_API_KEY: ${{ secrets.CI_AUTOBLOCKS_API_KEY }}
          AUTOBLOCKS_INGESTION_KEY: ${{ secrets.CI_AUTOBLOCKS_INGESTION_KEY }}

      - name: Run build
        run: npm run build

      - name: Install yalc
        run: npm install -g yalc

      - name: Publish
        run: yalc publish

      - name: Test CJS imports
        working-directory: e2e/test-import-cjs
        run: yalc add @autoblocks/client && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test

      - name: Test ESM imports
        working-directory: e2e/test-import-esm
        run: yalc add @autoblocks/client && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test
