name: CI

on: push

# Cancel in progress runs of this workflow when we push changes to the branch
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '18'
          - '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Validate renovate config
        run: npx --package renovate renovate-config-validator --strict

      - name: Install dependencies
        run: npm ci

      - name: Run type checks
        run: npm run type-check

      - name: Run lint checks
        run: npm run lint

      - name: Run tests
        run: npm run test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Run build
        run: npm run build

      - name: Install yalc
        run: npm install -g yalc

      - name: Yalc publish
        run: yalc publish

      - name: Delete top level node_modules
        run: rm -rf node_modules

      - name: Test CJS imports
        working-directory: e2e/test-import-cjs
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test

      - name: Test ESM imports
        working-directory: e2e/test-import-esm
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test

      - name: Test ESM imports frontend
        working-directory: e2e/test-import-esm-frontend
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_INGESTION_KEY: test

      - name: Test ESM imports & API client
        working-directory: e2e/test-api-client-esm
        run: yalc add @autoblocks/client && npm install && npm run start
        env:
          AUTOBLOCKS_API_KEY: ${{ secrets.CI_AUTOBLOCKS_API_KEY }}
          AUTOBLOCKS_INGESTION_KEY: ${{ secrets.CI_AUTOBLOCKS_INGESTION_KEY }}

      - name: Test Local Prompt Manager
        working-directory: e2e/test-local-prompt-manager-ts
        run: |
          yalc add @autoblocks/client && \
          npm install && \
          npm run gen && \
          tsc --noEmit && \
          npm run test

      - name: Test Headless Prompt Manager
        working-directory: e2e/test-headless-prompt-manager-ts
        run: |
          yalc add @autoblocks/client && \
          npm install && \
          npm run gen && \
          tsc --noEmit && \
          npm run test
        env:
          AUTOBLOCKS_API_KEY: ${{ secrets.CI_AUTOBLOCKS_API_KEY }}
