// This type will be autogenerated later by the user via a CLI command
// provided by this package.
// DO NOT CHANGE THE NAME OF THIS INTERFACE WITHOUT UPDATING THE CLI COMMAND.
export interface __AutogeneratedTemplatePathToParameters {}

// This type will be autogenerated later by the user via a CLI command
// provided by this package. It contains as keys the names of the templates
// without any placeholders.
// DO NOT CHANGE THE NAME OF THIS INTERFACE WITHOUT UPDATING THE CLI COMMAND.
export interface __AutogeneratedTemplatePathsWithNoPlaceholders {}

// This will be replaced via a CLI command after it's been compiled to JS.
// It will map the path of a template file to its contents.
// DO NOT CHANGE THE NAME OF THIS VARIABLE WITHOUT UPDATING THE CLI COMMAND.
export const __autogeneratedTemplatePathToTemplate: Record<string, string> = {};
