// These will be autogenerated later by the user via a CLI command provided by this package.
// DO NOT CHANGE THESE INTERFACES WITHOUT UPDATING THE CLI COMMAND.

// Map of app name -> prompt ID -> major version -> { templates, params, minorVersions }
interface __Autogenerated__PromptsV2Types {
  [key: string]: {
    [key: string]: {
      [key: string]: {
        templates: Record<string, Record<string, string>>;
        params: Record<string, unknown>;
        tools: Record<string, Record<string, string>>;
        minorVersions: string[];
      };
    };
  };
}

type HasTemplates<T> = T extends { templates: infer U } ? U : never;
type HasParams<T> = T extends { params: infer U } ? U : never;
type HasTools<T> = T extends { tools: infer U } ? U : never;
type HasMinorVersions<T> = T extends { minorVersions: infer U } ? U : never;

// App name to ID mapping
export const APP_NAME_TO_ID: Record<string, string> = {};

// Type for app names
export type __Autogenerated__AppName = keyof typeof APP_NAME_TO_ID;

export type __Autogenerated__AppId =
  (typeof APP_NAME_TO_ID)[__Autogenerated__AppName];

export type __Autogenerated__PromptIdV2<T extends __Autogenerated__AppName> =
  keyof __Autogenerated__PromptsV2Types[T] & string;

export type __Autogenerated__PromptMajorVersionV2<
  T extends __Autogenerated__AppName,
  U extends __Autogenerated__PromptIdV2<T>,
> = keyof __Autogenerated__PromptsV2Types[T][U] & string;

export type __Autogenerated__PromptMinorVersionV2<
  T extends __Autogenerated__AppName,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
> = HasMinorVersions<__Autogenerated__PromptsV2Types[T][U][V]> & string;

export type __Autogenerated__PromptTemplateIdV2<
  T extends __Autogenerated__AppName,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
> = keyof HasTemplates<__Autogenerated__PromptsV2Types[T][U][V]> & string;

export type __Autogenerated__PromptTemplateParamsV2<
  T extends __Autogenerated__AppName,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
  W extends __Autogenerated__PromptTemplateIdV2<T, U, V>,
> = HasTemplates<__Autogenerated__PromptsV2Types[T][U][V]>[W];

export type __Autogenerated__PromptParamsV2<
  T extends __Autogenerated__AppName,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
> = HasParams<__Autogenerated__PromptsV2Types[T][U][V]>;

export type __Autogenerated__PromptToolNameV2<
  T extends __Autogenerated__AppName,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
> = keyof HasTools<__Autogenerated__PromptsV2Types[T][U][V]> & string;

export type __Autogenerated__PromptToolParamsV2<
  T extends __Autogenerated__AppName,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
  W extends __Autogenerated__PromptToolNameV2<T, U, V>,
> = HasTools<__Autogenerated__PromptsV2Types[T][U][V]>[W];
