// These will be autogenerated later by the user via a CLI command provided by this package.
// DO NOT CHANGE THESE INTERFACES WITHOUT UPDATING THE CLI COMMAND.

// Map of appId -> prompt ID -> major version -> { templates, params, minorVersions }
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface __Autogenerated__PromptsV2Types {}

type HasTemplates<T> = T extends { templates: infer U } ? U : never;
type HasParams<T> = T extends { params: infer U } ? U : never;
type HasTools<T> = T extends { tools: infer U } ? U : never;
type HasMinorVersions<T> = T extends { minorVersions: infer U } ? U : never;

export type __Autogenerated__AppId = keyof __Autogenerated__PromptsV2Types &
  string;

export type __Autogenerated__PromptIdV2<T extends __Autogenerated__AppId> =
  keyof __Autogenerated__PromptsV2Types[T] & string;

export type __Autogenerated__PromptMajorVersionV2<
  T extends __Autogenerated__AppId,
  U extends __Autogenerated__PromptIdV2<T>,
> = keyof __Autogenerated__PromptsV2Types[T][U] & string;

export type __Autogenerated__PromptMinorVersionV2<
  T extends __Autogenerated__AppId,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
> = HasMinorVersions<__Autogenerated__PromptsV2Types[T][U][V]> & string;

export type __Autogenerated__PromptTemplateIdV2<
  T extends __Autogenerated__AppId,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
> = keyof HasTemplates<__Autogenerated__PromptsV2Types[T][U][V]> & string;

export type __Autogenerated__PromptTemplateParamsV2<
  T extends __Autogenerated__AppId,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
  W extends __Autogenerated__PromptTemplateIdV2<T, U, V>,
> = HasTemplates<__Autogenerated__PromptsV2Types[T][U][V]>[W];

export type __Autogenerated__PromptParamsV2<
  T extends __Autogenerated__AppId,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
> = HasParams<__Autogenerated__PromptsV2Types[T][U][V]>;

export type __Autogenerated__PromptToolNameV2<
  T extends __Autogenerated__AppId,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
> = keyof HasTools<__Autogenerated__PromptsV2Types[T][U][V]> & string;

export type __Autogenerated__PromptToolParamsV2<
  T extends __Autogenerated__AppId,
  U extends __Autogenerated__PromptIdV2<T>,
  V extends __Autogenerated__PromptMajorVersionV2<T, U>,
  W extends __Autogenerated__PromptToolNameV2<T, U, V>,
> = HasTools<__Autogenerated__PromptsV2Types[T][U][V]>[W];
