// These will be autogenerated later by the user via a CLI command provided by this package.
// DO NOT CHANGE THESE INTERFACES WITHOUT UPDATING THE CLI COMMAND.

// Map of prompt ID -> major version -> { templates, params, minorVersions }
interface __Autogenerated__PromptsTypes {}

type HasTemplates<T> = T extends { templates: infer U } ? U : never;
type HasParams<T> = T extends { params: infer U } ? U : never;
type HasMinorVersions<T> = T extends { minorVersions: infer U } ? U : never;

export type __Autogenerated__PromptId = keyof __Autogenerated__PromptsTypes &
  string;
export type __Autogenerated__PromptMajorVersion<
  T extends __Autogenerated__PromptId,
> = keyof __Autogenerated__PromptsTypes[T] & string;
export type __Autogenerated__PromptMinorVersion<
  T extends __Autogenerated__PromptId,
  U extends __Autogenerated__PromptMajorVersion<T>,
> = HasMinorVersions<__Autogenerated__PromptsTypes[T][U]> & string;
export type __Autogenerated__PromptTemplateId<
  T extends __Autogenerated__PromptId,
  U extends __Autogenerated__PromptMajorVersion<T>,
> = keyof HasTemplates<__Autogenerated__PromptsTypes[T][U]> & string;
export type __Autogenerated__PromptTemplateParams<
  T extends __Autogenerated__PromptId,
  U extends __Autogenerated__PromptMajorVersion<T>,
  V extends __Autogenerated__PromptTemplateId<T, U>,
> = HasTemplates<__Autogenerated__PromptsTypes[T][U]>[V];
export type __Autogenerated__PromptParams<
  T extends __Autogenerated__PromptId,
  U extends __Autogenerated__PromptMajorVersion<T>,
> = HasParams<__Autogenerated__PromptsTypes[T][U]>;
