export { AutoblocksPromptManager } from './manager';
export { AutoblocksPromptManagerV2 } from './manager-v2';

export type {
  __Autogenerated__PromptId as PromptId,
  __Autogenerated__PromptMajorVersion as PromptMajorVersion,
  __Autogenerated__PromptMinorVersion as PromptMinorVersion,
} from './autogenerated';

// Export V2 types
export type {
  __Autogenerated__AppId as AppId,
  __Autogenerated__PromptIdV2 as PromptIdV2,
  __Autogenerated__PromptMajorVersionV2 as PromptMajorVersionV2,
  __Autogenerated__PromptMinorVersionV2 as PromptMinorVersionV2,
  __Autogenerated__PromptTemplateIdV2 as PromptTemplateIdV2,
  __Autogenerated__PromptTemplateParamsV2 as PromptTemplateParamsV2,
  __Autogenerated__PromptParamsV2 as PromptParamsV2,
  __Autogenerated__PromptToolNameV2 as PromptToolNameV2,
  __Autogenerated__PromptToolParamsV2 as PromptToolParamsV2,
} from './autogenerated-v2';
